spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_IAM_ACCESS_KEY}
        secret-key: ${AWS_IAM_SECRET_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_S3_REGION}