name: Build and Docker Push

on:
  workflow_dispatch:
  push:
    branches:
      - feat/workflow
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Generate image tags
        id: tags
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "version=${TIMESTAMP}" >> $GITHUB_OUTPUT
          echo "latest=latest" >> $GITHUB_OUTPUT

      # ECR 접근을 위한 AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          REGION=${{ secrets.AWS_REGION }}
          ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG="latest"
          
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG