name: Redis and RabbitMQ to ECR

on:
  workflow_dispatch:
  push:
    branches:
      - feat/workflow
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  REDIS_IMAGE_NAME: redis
  RABBITMQ_IMAGE_NAME: rabbitmq

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions

      - name: Build with Gradle
        run: ./gradlew bootJar

      # Redis 빌드 및 푸시
      - name: Build Redis Docker image
        run: docker build -t "$ECR_REGISTRY/$REDIS_IMAGE_NAME:latest" -f Dockerfile .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Redis Docker image to ECR
        run: docker push "$ECR_REGISTRY/$REDIS_IMAGE_NAME:latest"

      # RabbitMQ 빌드 및 푸시
      - name: Build RabbitMQ Docker image
        run: docker build -t "$ECR_REGISTRY/$RABBITMQ_IMAGE_NAME:latest" -f Dockerfile .

      - name: Push RabbitMQ Docker image to ECR
        run: docker push "$ECR_REGISTRY/$RABBITMQ_IMAGE_NAME:latest"

      - name: Save image URIs
        id: save-image-uris
        run: |
          echo "REDIS_IMAGE_URI=$ECR_REGISTRY/$REDIS_IMAGE_NAME:latest" >> $GITHUB_OUTPUT
          echo "RABBITMQ_IMAGE_URI=$ECR_REGISTRY/$RABBITMQ_IMAGE_NAME:latest" >> $GITHUB_OUTPUT

      - name: Upload image URIs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: redis-rabbitmq-image-uris
          path: .github/workflows/output/redis_rabbitmq_image_uris.txt
          if: always()
        continue-on-error: true